(() => {
  'use strict';

  const copy = {
    en: {
      welcome:'Assalam-o-Alaikum! I can check live available properties for you. What would you like?', property:'Find an available property', agents:'Property dealers & agents', lead:'Request a callback', whatsapp:'Chat on WhatsApp', whatsappMessage:'Assalam-o-Alaikum, I need information about a property.', ask:'Type your question…', typeQuestion:'What do you want: a plot/land, house, apartment, villa, or condo?', sizeQuestion:'What size do you need? For example: 3 Marla, 5 Marla, 10 Marla, or any size.', anySize:'Any size', noProperty:'That property is not currently available in the published listings. Try another type or size, or request a callback.', noAgents:'No published agents are available right now.', name:'Please enter your name.', phone:'Thanks! Now enter your phone or WhatsApp number.', invalidName:'Please enter at least 2 characters for your name.', invalidPhone:'Please enter a valid phone number with 10 to 15 digits.', saved:'Thank you! Your message is saved. Our property dealer will contact you shortly.', error:'Sorry, I could not complete that request. Please try again.', results:'Available properties matching your request:', agentIntro:'Here are our published property dealers and agents:', help:'You can also type a full request, for example “5 Marla plot in Lahore for sale”.', available:'Available', open:'Open property details', again:'Search again', greeting:'Wa-Alaikum-Assalam! I am ready to help you find an available property.', thanks:'You are welcome. Would you like to search another property or request a callback?'
    },
    ur: {
      welcome:'السلام علیکم! میں دستیاب پراپرٹیز فوراً چیک کر سکتا ہوں۔ آپ کیا چاہتے ہیں؟', property:'دستیاب پراپرٹی تلاش کریں', agents:'پراپرٹی ڈیلرز اور ایجنٹس', lead:'کال کی درخواست', whatsapp:'واٹس ایپ پر رابطہ کریں', whatsappMessage:'السلام علیکم، مجھے پراپرٹی کے بارے میں معلومات چاہیے۔', ask:'اپنا سوال لکھیں…', typeQuestion:'آپ کیا چاہتے ہیں: پلاٹ/زمین، گھر، اپارٹمنٹ، ولا یا کونڈو؟', sizeQuestion:'آپ کو کون سا سائز چاہیے؟ مثال: 3 مرلہ، 5 مرلہ، 10 مرلہ یا کوئی بھی سائز۔', anySize:'کوئی بھی سائز', noProperty:'یہ پراپرٹی اس وقت شائع شدہ فہرست میں دستیاب نہیں۔ دوسرا سائز یا قسم تلاش کریں، یا کال کی درخواست دیں۔', noAgents:'اس وقت کوئی شائع شدہ ایجنٹ موجود نہیں۔', name:'براہ کرم اپنا نام لکھیں۔', phone:'شکریہ! اب اپنا فون یا واٹس ایپ نمبر لکھیں۔', invalidName:'نام میں کم از کم 2 حروف لکھیں۔', invalidPhone:'10 سے 15 ہندسوں کا درست فون نمبر لکھیں۔', saved:'شکریہ! آپ کا پیغام محفوظ ہوگیا۔ ہمارا ڈیلر جلد رابطہ کرے گا۔', error:'معذرت، درخواست مکمل نہیں ہو سکی۔ دوبارہ کوشش کریں۔', results:'آپ کی درخواست کے مطابق دستیاب پراپرٹیز:', agentIntro:'ہمارے شائع شدہ پراپرٹی ڈیلرز اور ایجنٹس:', help:'آپ مکمل درخواست بھی لکھ سکتے ہیں، مثال: لاہور میں فروخت کے لیے 5 مرلہ پلاٹ۔', available:'دستیاب', open:'پراپرٹی کی مکمل تفصیل', again:'دوبارہ تلاش', greeting:'وعلیکم السلام! میں دستیاب پراپرٹی تلاش کرنے کے لیے تیار ہوں۔', thanks:'خوش آمدید۔ کیا آپ دوسری پراپرٹی تلاش کرنا یا کال کی درخواست دینا چاہتے ہیں؟'
    },
    roman: {
      welcome:'Assalam-o-Alaikum! Main live available properties check kar sakta hoon. Aap kya chahte hain?', property:'Available property talash karein', agents:'Property dealers aur agents', lead:'Call ki request', whatsapp:'WhatsApp par rabta karein', whatsappMessage:'Assalam-o-Alaikum, mujhe property ke bare mein maloomat chahiye.', ask:'Apna sawal likhein…', typeQuestion:'Aap kya chahte hain: plot/land, house, apartment, villa ya condo?', sizeQuestion:'Aap ko kitna size chahiye? Misal: 3 Marla, 5 Marla, 10 Marla ya koi bhi size.', anySize:'Koi bhi size', noProperty:'Yeh property abhi published listings mein available nahi hai. Doosra type ya size try karein, ya callback mangwain.', noAgents:'Abhi koi published agent available nahi hai.', name:'Apna naam likhein.', phone:'Shukriya! Ab apna phone ya WhatsApp number likhein.', invalidName:'Naam mein kam az kam 2 letters likhein.', invalidPhone:'10 se 15 digits ka valid phone number likhein.', saved:'Shukriya! Aap ka message save ho gaya. Hamara dealer jald rabta karega.', error:'Maazrat, request complete nahi ho saki. Dobara try karein.', results:'Aap ki request ke mutabiq available properties:', agentIntro:'Hamare published property dealers aur agents:', help:'Aap poora sawal bhi likh sakte hain, misal: Lahore mein sale ke liye 5 Marla plot.', available:'Available', open:'Property ki poori detail', again:'Dobara search', greeting:'Wa-Alaikum-Assalam! Main available property talash karne ke liye tayyar hoon.', thanks:'Khush aamdeed. Kya aap doosri property search karna ya callback lena chahte hain?'
    }
  };

  let language=localStorage.getItem('heeraChatLanguage')||'',mode='',properties=[],agents=[],criteria={type:'',size:'',listing:''},conversation=[],lastPropertyId=null,dataPromise=null;
  let lead={name:'',phone:'',message:'',property_id:null};
  document.body.insertAdjacentHTML('beforeend',`<button class="heera-chat-launcher" type="button" aria-label="Open property assistant" aria-expanded="false">💬</button><section class="heera-chat" role="dialog" aria-label="Heera Estate property assistant"><header class="heera-chat-header"><span class="heera-chat-avatar">⌂</span><div class="heera-chat-title"><strong>Heera Estate Assistant</strong><small>● Online — live property data</small></div><button class="heera-chat-close" type="button" aria-label="Close chat">×</button></header><div class="heera-chat-messages" aria-live="polite"></div><a class="heera-chat-whatsapp" href="#" target="_blank" rel="noopener"><span aria-hidden="true">◉</span><b>Chat on WhatsApp</b></a><form class="heera-chat-form"><input class="heera-chat-input" autocomplete="off" maxlength="300" aria-label="Chat message"><button class="heera-chat-send" type="submit" aria-label="Send">➜</button><input name="website" tabindex="-1" autocomplete="off" hidden></form><div class="heera-chat-powered">Free multilingual property assistant</div></section>`);
  const panel=document.querySelector('.heera-chat'),launcher=document.querySelector('.heera-chat-launcher'),messages=document.querySelector('.heera-chat-messages'),input=document.querySelector('.heera-chat-input'),form=document.querySelector('.heera-chat-form'),whatsapp=document.querySelector('.heera-chat-whatsapp');
  const t=key=>copy[language||'en'][key],escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])),scroll=()=>{messages.scrollTop=messages.scrollHeight;};
  function say(text,who='bot'){messages.insertAdjacentHTML('beforeend',`<div class="heera-chat-message ${who}"><div class="heera-chat-bubble">${escapeHtml(text)}</div></div>`);scroll();}
  function choices(items){const row=document.createElement('div');row.className='heera-chat-choices';items.forEach(([label,action])=>{const button=document.createElement('button');button.type='button';button.className='heera-chat-choice';button.textContent=label;button.addEventListener('click',action);row.appendChild(button);});messages.appendChild(row);scroll();}
  function mainChoices(){choices([[t('property'),startPropertySearch],[t('agents'),showAgents],[t('lead'),startLead]]);}
  function updateWhatsapp(){whatsapp.href=`https://wa.me/923000660446?text=${encodeURIComponent(t('whatsappMessage'))}`;whatsapp.querySelector('b').textContent=t('whatsapp');}
  async function loadData(){const [p,a]=await Promise.all([fetch('api.php?action=properties'),fetch('api.php?action=agents')]);if(p.ok)properties=await p.json();if(a.ok)agents=await a.json();}
  function start(){if(!language){say('Welcome / خوش آمدید');choices([['English',()=>setLanguage('en')],['اردو',()=>setLanguage('ur')],['Roman Urdu',()=>setLanguage('roman')]]);}else{say(t('welcome'));mainChoices();}dataPromise=dataPromise||loadData();dataPromise.catch(()=>{});}
  function setLanguage(value){language=value;localStorage.setItem('heeraChatLanguage',value);messages.innerHTML='';input.placeholder=t('ask');updateWhatsapp();say(t('welcome'));mainChoices();}
  function formatPrice(item){const amount=Number(item.price_pkr||item.price||0);if(!amount)return 'Price on request';return item.price_pkr?`PKR ${amount.toLocaleString('en-PK')}`:`$${amount.toLocaleString('en-US')}`;}
  function normalize(value){const aliases={'لاہور':'lahore','کراچی':'karachi','اسلام آباد':'islamabad','راولپنڈی':'rawalpindi','پلاٹ':'land','زمین':'land','گھر':'house','مکان':'house','اپارٹمنٹ':'apartment','ولا':'villa','فروخت':'sale','خرید':'sale','کرایہ':'rent','مرلہ':'marla','zameen':'land','plot':'land','ghar':'house','makaan':'house','khareed':'sale','kiraya':'rent'};let result=String(value||'').toLowerCase();Object.entries(aliases).forEach(([from,to])=>{result=result.split(from).join(to);});return result.replace(/\s+/g,' ').trim();}
  function detectType(value){const n=normalize(value);if(/\b(plot|land|zameen)\b/.test(n))return'Land';if(/\b(house|home|ghar|makaan)\b/.test(n))return'House';if(/\b(apartment|flat)\b/.test(n))return'Apartment';if(/\bvilla\b/.test(n))return'Villa';if(/\bcondo\b/.test(n))return'Condo';return'';}
  function detectListing(value){const n=normalize(value);if(/\b(rent|rental|kiraya)\b/.test(n))return'rent';if(/\b(sale|buy|purchase|khareed)\b/.test(n))return'sale';return'';}
  function detectSize(value){const n=normalize(value),match=n.match(/(\d+(?:\.\d+)?)\s*(marla|kanal|sq\.?\s*ft|sqft|square feet)/);return match?`${match[1]} ${match[2].replace(/sq\.?\s*ft|square feet/,'sqft')}`:'';}
  function propertyScore(item,query){const n=normalize(query),text=normalize([item.title,item.city,item.state_region,item.address_line1,item.block_name,item.property_type,item.listing_type,item.size_label,item.property_facing,item.description].join(' '));return n.replace(/[^a-z0-9.]+/g,' ').split(' ').filter(word=>word.length>1).reduce((score,word)=>score+(text.includes(word)?2:0),0);}
  function startPropertySearch(){criteria={type:'',size:'',listing:''};mode='search-type';say(t('typeQuestion'));choices([['Plot / Land',()=>acceptType('Land')],['House',()=>acceptType('House')],['Apartment',()=>acceptType('Apartment')],['Villa',()=>acceptType('Villa')]]);input.focus();}
  function acceptType(value){criteria.type=detectType(value)||String(value||'').trim();criteria.listing=detectListing(value);conversation.push(`Wanted property type: ${criteria.type||value}`);mode='search-size';say(t('sizeQuestion'));choices([['3 Marla',()=>acceptSize('3 Marla')],['5 Marla',()=>acceptSize('5 Marla')],['10 Marla',()=>acceptSize('10 Marla')],[t('anySize'),()=>acceptSize('')]]);input.focus();}
  function acceptSize(value){criteria.size=detectSize(value)||String(value||'').trim();conversation.push(`Wanted size: ${criteria.size||'Any size'}`);mode='';showProperties([criteria.type,criteria.size,criteria.listing].filter(Boolean).join(' '),criteria);}
  async function showProperties(query,filters={}){try{if(!properties.length){dataPromise=dataPromise||loadData();await dataPromise;}}catch{say(t('error'));return;}const type=filters.type||detectType(query),size=filters.size||detectSize(query),listing=filters.listing||detectListing(query);conversation.push(`Property search: ${query}`);let ranked=properties.map(item=>({item,score:propertyScore(item,query)}));if(type)ranked=ranked.filter(({item})=>normalize(item.property_type)===normalize(type));if(size)ranked=ranked.filter(({item})=>normalize(item.size_label).includes(normalize(size)));if(listing)ranked=ranked.filter(({item})=>item.listing_type===listing);if(!type&&!size&&!listing)ranked=ranked.filter(({score})=>score>0);ranked=ranked.sort((a,b)=>b.score-a.score).slice(0,5);if(!ranked.length){lastPropertyId=null;say(t('noProperty'));choices([[t('again'),startPropertySearch],[t('lead'),startLead]]);return;}lastPropertyId=Number(ranked[0].item.property_id)||null;say(t('results'));ranked.forEach(({item})=>{const card=document.createElement('a');card.className='heera-chat-card heera-property-result';card.href=`property.html?id=${encodeURIComponent(item.property_id)}`;card.innerHTML=`<strong>${escapeHtml(item.title)}</strong><span class="heera-available">● ${escapeHtml(t('available'))}</span><span>${escapeHtml([item.listing_type==='rent'?'For rent':'For sale',item.property_type,item.size_label,item.block_name,item.city,item.property_facing,formatPrice(item)].filter(Boolean).join(' · '))}</span><b>${escapeHtml(t('open'))} →</b>`;messages.appendChild(card);});choices([[t('again'),startPropertySearch],[t('lead'),startLead]]);scroll();}
  async function showAgents(){mode='';try{if(!agents.length){dataPromise=dataPromise||loadData();await dataPromise;}}catch{say(t('error'));return;}if(!agents.length){say(t('noAgents'));return;}say(t('agentIntro'));agents.slice(0,8).forEach(agent=>{const card=document.createElement('div');card.className='heera-chat-card';card.innerHTML=`<strong>${escapeHtml(agent.name)}</strong><span>${escapeHtml([agent.title,agent.phone,agent.email].filter(Boolean).join(' · '))}</span>`;messages.appendChild(card);});scroll();}
  function startLead(){mode='lead-name';lead={name:'',phone:'',message:conversation.slice(-10).join('\n'),property_id:lastPropertyId};say(t('name'));input.focus();}
  async function submitLead(){try{const response=await fetch('api.php?action=chat_lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...lead,language,website:''})});const result=await response.json();if(!response.ok)throw new Error(result.error);say(t('saved'));mode='';conversation=[];mainChoices();}catch(error){say(error.message||t('error'));}}
  function handle(text){say(text,'user');if(mode==='lead-name'){if(text.trim().length<2){say(t('invalidName'));return;}lead.name=text.trim();mode='lead-phone';say(t('phone'));return;}if(mode==='lead-phone'){const digits=text.replace(/\D/g,'');if(digits.length<10||digits.length>15){say(t('invalidPhone'));return;}lead.phone=text.trim();submitLead();return;}if(mode==='search-type'){acceptType(text);return;}if(mode==='search-size'){acceptSize(/any|koi|کوئی/.test(normalize(text))?'':text);return;}const n=normalize(text);if(/\b(agent|dealer)\b|ایجنٹ|ڈیلر/.test(n))return showAgents();if(/\b(call|contact|phone|callback|number)\b|رابط|کال|نمبر/.test(n))return startLead();if(/^(hi|hello|salam|assalam|السلام)/.test(n)){say(t('greeting'));mainChoices();return;}if(/thank|thanks|shukriya|شکریہ/.test(n)){say(t('thanks'));mainChoices();return;}const type=detectType(text),size=detectSize(text);if(!type&&!size&&/help|madad|مدد/.test(n)){say(t('help'));mainChoices();return;}showProperties(text);}
  updateWhatsapp();
  launcher.addEventListener('click',()=>{const open=panel.classList.toggle('is-open');launcher.setAttribute('aria-expanded',String(open));if(open){if(!messages.children.length)start();input.placeholder=t('ask');input.focus();}});
  document.querySelector('.heera-chat-close').addEventListener('click',()=>{panel.classList.remove('is-open');launcher.setAttribute('aria-expanded','false');launcher.focus();});
  form.addEventListener('submit',event=>{event.preventDefault();const text=input.value.trim();if(!text)return;input.value='';handle(text);});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&panel.classList.contains('is-open'))document.querySelector('.heera-chat-close').click();});
})();
