(() => {
  'use strict';

  const copy = {
    en: { welcome: 'Assalam-o-Alaikum! I am the Heera Estate assistant. How can I help?', property: 'Search properties', agents: 'Property dealers & agents', lead: 'Request a callback', ask: 'Type your question…', noProperty: 'I could not find an exact match. Try a city, property type, sale, rent, or plot size.', noAgents: 'No published agents are available right now.', name: 'Please enter your name.', phone: 'Thanks! Now enter your phone number.', saved: 'Thank you! Our property dealer will contact you shortly.', error: 'Sorry, I could not complete that request. Please try again.', results: 'Here are the best matches:', agentIntro: 'Here are our property dealers and agents:', help: 'You can ask for properties by city, type, sale/rent, price, or size. Example: “5 Marla plot in Lahore”.' },
    ur: { welcome: 'السلام علیکم! میں ہیرا اسٹیٹ اسسٹنٹ ہوں۔ میں آپ کی کیا مدد کر سکتا ہوں؟', property: 'پراپرٹی تلاش کریں', agents: 'پراپرٹی ڈیلرز اور ایجنٹس', lead: 'کال کی درخواست', ask: 'اپنا سوال لکھیں…', noProperty: 'کوئی بالکل مطابق پراپرٹی نہیں ملی۔ شہر، پراپرٹی کی قسم، فروخت، کرایہ یا پلاٹ سائز لکھیں۔', noAgents: 'اس وقت کوئی شائع شدہ ایجنٹ موجود نہیں۔', name: 'براہ کرم اپنا نام لکھیں۔', phone: 'شکریہ! اب اپنا فون نمبر لکھیں۔', saved: 'شکریہ! ہمارا پراپرٹی ڈیلر جلد آپ سے رابطہ کرے گا۔', error: 'معذرت، درخواست مکمل نہیں ہو سکی۔ دوبارہ کوشش کریں۔', results: 'یہ بہترین نتائج ہیں:', agentIntro: 'ہمارے پراپرٹی ڈیلرز اور ایجنٹس:', help: 'آپ شہر، قسم، فروخت/کرایہ، قیمت یا سائز سے پراپرٹی تلاش کر سکتے ہیں۔ مثال: لاہور میں 5 مرلہ پلاٹ۔' },
    roman: { welcome: 'Assalam-o-Alaikum! Main Heera Estate assistant hoon. Main aap ki kya madad kar sakta hoon?', property: 'Property talash karein', agents: 'Property dealers aur agents', lead: 'Call ki request', ask: 'Apna sawal likhein…', noProperty: 'Exact property nahi mili. Shehar, property type, sale, rent ya plot size likhein.', noAgents: 'Abhi koi published agent available nahi hai.', name: 'Apna naam likhein.', phone: 'Shukriya! Ab apna phone number likhein.', saved: 'Shukriya! Hamara property dealer jald aap se rabta karega.', error: 'Maazrat, request complete nahi ho saki. Dobara try karein.', results: 'Yeh best matches hain:', agentIntro: 'Hamare property dealers aur agents:', help: 'Aap city, type, sale/rent, price ya size se property search kar sakte hain. Misal: Lahore mein 5 Marla plot.' }
  };

  let language = localStorage.getItem('heeraChatLanguage') || '';
  let mode = '';
  let lead = { name: '', phone: '' };
  let properties = [];
  let agents = [];

  document.body.insertAdjacentHTML('beforeend', `<button class="heera-chat-launcher" type="button" aria-label="Open property assistant" aria-expanded="false">💬</button><section class="heera-chat" role="dialog" aria-label="Heera Estate property assistant"><header class="heera-chat-header"><span class="heera-chat-avatar">⌂</span><div class="heera-chat-title"><strong>Heera Estate Assistant</strong><small>● Online — instant replies</small></div><button class="heera-chat-close" type="button" aria-label="Close chat">×</button></header><div class="heera-chat-messages" aria-live="polite"></div><form class="heera-chat-form"><input class="heera-chat-input" autocomplete="off" maxlength="300" aria-label="Chat message"><button class="heera-chat-send" type="submit" aria-label="Send">➜</button><input name="website" tabindex="-1" autocomplete="off" hidden></form><div class="heera-chat-powered">Free multilingual property assistant</div></section>`);

  const panel = document.querySelector('.heera-chat');
  const launcher = document.querySelector('.heera-chat-launcher');
  const messages = document.querySelector('.heera-chat-messages');
  const input = document.querySelector('.heera-chat-input');
  const form = document.querySelector('.heera-chat-form');

  const t = key => copy[language || 'en'][key];
  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const scroll = () => { messages.scrollTop = messages.scrollHeight; };
  function say(text, who = 'bot') { messages.insertAdjacentHTML('beforeend', `<div class="heera-chat-message ${who}"><div class="heera-chat-bubble">${escapeHtml(text)}</div></div>`); scroll(); }
  function choices(items) { const row = document.createElement('div'); row.className = 'heera-chat-choices'; items.forEach(([label, action]) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'heera-chat-choice'; button.textContent = label; button.addEventListener('click', action); row.appendChild(button); }); messages.appendChild(row); scroll(); }
  function mainChoices() { choices([[t('property'), () => { mode = 'property'; say(t('help')); input.focus(); }], [t('agents'), showAgents], [t('lead'), startLead]]); }
  async function loadData() { const [propertyResponse, agentResponse] = await Promise.all([fetch('api.php?action=properties'), fetch('api.php?action=agents')]); if (propertyResponse.ok) properties = await propertyResponse.json(); if (agentResponse.ok) agents = await agentResponse.json(); }
  function start() { if (!language) { say('Welcome / خوش آمدید'); choices([['English', () => setLanguage('en')], ['اردو', () => setLanguage('ur')], ['Roman Urdu', () => setLanguage('roman')]]); } else { say(t('welcome')); mainChoices(); } loadData().catch(() => {}); }
  function setLanguage(value) { language = value; localStorage.setItem('heeraChatLanguage', value); messages.innerHTML = ''; input.placeholder = t('ask'); say(t('welcome')); mainChoices(); }
  function formatPrice(item) { const amount = Number(item.price_pkr || item.price || 0); if (!amount) return ''; return item.price_pkr ? `PKR ${amount.toLocaleString('en-PK')}` : `$${amount.toLocaleString('en-US')}`; }
  function propertyScore(item, query) { const aliases = {'لاہور':'lahore','کراچی':'karachi','اسلام آباد':'islamabad','راولپنڈی':'rawalpindi','زفروال':'zafarwal','پلاٹ':'land','زمین':'land','گھر':'house','مکان':'house','فروخت':'sale','خرید':'sale','کرایہ':'rent','مرلہ':'marla','zameen':'land','plot':'land','ghar':'house','khareed':'sale','kiraya':'rent'}; let normalized = query.toLowerCase(); Object.entries(aliases).forEach(([from,to]) => { normalized = normalized.split(from).join(to); }); const text = [item.title,item.city,item.state_region,item.address_line1,item.property_type,item.listing_type,item.size_label,item.property_facing,item.status].join(' ').toLowerCase(); const words = normalized.replace(/[^a-z0-9\u0600-\u06ff.]+/g,' ').split(' ').filter(word => word.length > 1); return words.reduce((score, word) => score + (text.includes(word) ? 2 : 0), 0); }
  function showProperties(query) { const ranked = properties.map(item => ({item, score: propertyScore(item, query)})).filter(result => result.score > 0).sort((a,b) => b.score - a.score).slice(0,4); if (!ranked.length) { say(t('noProperty')); return; } say(t('results')); ranked.forEach(({item}) => { const card = document.createElement('a'); card.className = 'heera-chat-card'; card.href = `property.html?id=${encodeURIComponent(item.property_id)}`; card.innerHTML = `<strong>${escapeHtml(item.title)}</strong><span>${escapeHtml([item.size_label,item.property_type,item.city,formatPrice(item)].filter(Boolean).join(' · '))}</span>`; messages.appendChild(card); }); choices([[t('lead'), startLead]]); scroll(); }
  function showAgents() { mode = ''; if (!agents.length) { say(t('noAgents')); return; } say(t('agentIntro')); agents.slice(0,8).forEach(agent => { const card = document.createElement('div'); card.className = 'heera-chat-card'; const contact = [agent.title,agent.phone,agent.email].filter(Boolean).join(' · '); card.innerHTML = `<strong>${escapeHtml(agent.name)}</strong><span>${escapeHtml(contact)}</span>`; messages.appendChild(card); }); scroll(); }
  function startLead() { mode = 'lead-name'; lead = {name:'',phone:''}; say(t('name')); input.focus(); }
  async function submitLead() { try { const response = await fetch('api.php?action=chat_lead', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...lead,language,website:''})}); const result = await response.json(); if (!response.ok) throw new Error(result.error); say(t('saved')); mode = ''; mainChoices(); } catch (error) { say(error.message || t('error')); } }
  function handle(text) { say(text, 'user'); if (mode === 'lead-name') { lead.name = text.trim(); mode = 'lead-phone'; say(t('phone')); return; } if (mode === 'lead-phone') { lead.phone = text.trim(); submitLead(); return; } const normalized = text.toLowerCase(); if (/agent|dealer|ایجنٹ|ڈیلر/.test(normalized)) return showAgents(); if (/call|contact|phone|رابط|کال|number|نمبر/.test(normalized)) return startLead(); showProperties(text); }

  launcher.addEventListener('click', () => { const open = panel.classList.toggle('is-open'); launcher.setAttribute('aria-expanded', String(open)); if (open) { if (!messages.children.length) start(); input.placeholder = t('ask'); input.focus(); } });
  document.querySelector('.heera-chat-close').addEventListener('click', () => { panel.classList.remove('is-open'); launcher.setAttribute('aria-expanded','false'); launcher.focus(); });
  form.addEventListener('submit', event => { event.preventDefault(); const text = input.value.trim(); if (!text) return; input.value = ''; handle(text); });
  document.addEventListener('keydown', event => { if (event.key === 'Escape' && panel.classList.contains('is-open')) document.querySelector('.heera-chat-close').click(); });
})();
