(() => {
  const form=document.querySelector('#clientPropertyForm'),files=document.querySelector('#clientImages'),video=document.querySelector('#clientVideo'),preview=document.querySelector('#clientPreview'),message=document.querySelector('#clientFormMessage'),type=document.querySelector('#clientPropertyType');
  form.hidden=true;
  fetch('api.php?action=account_session',{credentials:'same-origin',headers:{Accept:'application/json'}}).then(response=>response.json()).then(session=>{if(!session.authenticated){window.location.href='index.html?return=client-form.html#login';return;}form.hidden=false;}).catch(()=>{window.location.href='index.html?return=client-form.html#login';});
  const today=new Date().toISOString().slice(0,10),start=document.querySelector('#publishStartDate'),end=document.querySelector('#publishEndDate');start.min=today;end.min=today;start.value=today;start.addEventListener('change',()=>{end.min=start.value||today;if(end.value&&end.value<end.min)end.value=end.min;});
  function updateType(){document.querySelectorAll('.home-detail').forEach(field=>field.hidden=type.value==='Land');} type.addEventListener('change',updateType);updateType();
  files.addEventListener('change',()=>{preview.innerHTML='';const selected=[...files.files];if(selected.length>5){message.textContent='Please select no more than 5 images.';files.value='';return;}message.textContent='';selected.forEach(file=>{const image=document.createElement('img');image.alt='Selected property photo';image.src=URL.createObjectURL(file);image.onload=()=>URL.revokeObjectURL(image.src);preview.appendChild(image);});});
  video.addEventListener('change',()=>{const file=video.files[0],label=document.querySelector('#clientVideoName');if(!file){label.textContent='';return;}if(file.size>=100*1024*1024){message.textContent='Video must be smaller than 100 MB.';video.value='';label.textContent='';return;}message.textContent='';label.textContent=`Selected: ${file.name} (${(file.size/1024/1024).toFixed(1)} MB)`;});
  form.addEventListener('submit',async event=>{event.preventDefault();if(end.value<start.value){message.textContent='End date must be the same as or later than the start date.';return;}const button=form.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Uploading and sending…';message.textContent='';try{const response=await fetch('api.php?action=submit_property',{method:'POST',body:new FormData(form),credentials:'same-origin'});const result=await response.json();if(response.status===401){window.location.href='index.html?return=client-form.html#login';return;}if(!response.ok)throw new Error(result.error||'Submission failed.');form.hidden=true;document.querySelector('#clientSuccess').hidden=false;document.querySelector('#clientReference').textContent=`Reference: ${result.reference}`;}catch(error){message.textContent=error.message;button.disabled=false;button.innerHTML='Send for approval <span>→</span>';}});
})();
