<?php
declare(strict_types=1); require_once __DIR__.'/seo.php';
$slug=trim((string)($_GET['slug']??''));$id=(int)($_GET['id']??0);$subProjectId=(int)($_GET['sub_project_id']??0);$subProjectSlug=trim((string)($_GET['sub_project_slug']??''));$directSubProjectRequest=$subProjectSlug!=='';
try{$pdo=seo_db();if($subProjectSlug!==''||($slug===''&&$id<1&&$subProjectId>0)){$reference=seo_fetch_published_sub_project($pdo,$subProjectSlug?:null,$subProjectId);if($reference){$id=(int)$reference['project_id'];$slug='';$subProjectId=(int)$reference['sub_project_id'];}}$project=seo_fetch_project($pdo,$slug?:null,$id);if($project)$project=seo_select_project_sub_project($project,$subProjectId);}catch(Throwable $e){$project=null;}
if(!$project)http_response_code(404);
$selectedSubProject=$project['selected_sub_project']??null;$subProjectName=trim((string)($selectedSubProject['name']??''));$selectedSubProjectSlug=trim((string)($selectedSubProject['slug']??''));
if($project&&!$directSubProjectRequest&&$slug===''&&$id>0&&!empty($project['slug'])){$destination=$selectedSubProjectSlug!==''?seo_url('sub-project/'.$selectedSubProjectSlug):seo_url('project/'.$project['slug']);header('Location: '.$destination,true,301);exit;}
$display=$project?trim($project['title'].($subProjectName!==''?' – '.$subProjectName:(($project['plan_name']??'')!==''?' – '.$project['plan_name']:''))):'';$title=$project?$display.' Property Project in '.$project['location'].' | '.seo_site_name():'Project not found | '.seo_site_name();$description=$project?seo_description(($selectedSubProject['description']??'')?:($project['description']?:('Explore '.$display.', a '.$project['category'].' real-estate project in '.$project['location'].'. View sub-projects, property plans, gallery and map details.'))):'The requested project is unavailable.';$projectPath=$project&&!empty($project['slug'])?'project/'.$project['slug']:'project.php?id='.(int)($project['project_id']??0);$canonical=$project?seo_url($selectedSubProjectSlug!==''?'sub-project/'.$selectedSubProjectSlug:$projectPath):seo_url('project');$cover=$project?($project['hero_image_url']?:($project['media'][0]['file_path']??'')):'';
$crumbs=[['name'=>'Home','url'=>seo_url()],['name'=>'Projects','url'=>seo_url('#projects')]];if($project){$crumbs[]=['name'=>$project['title'],'url'=>seo_url($projectPath)];if($subProjectName!=='')$crumbs[]=['name'=>$subProjectName,'url'=>$canonical];}
$schema=$project?['@context'=>'https://schema.org','@type'=>'RealEstateListing','@id'=>$canonical.'#listing','name'=>$display,'description'=>$description,'url'=>$canonical,'mainEntityOfPage'=>$canonical,'image'=>seo_asset_url($cover),'dateModified'=>$project['updated_at'],'inLanguage'=>'en-PK','provider'=>['@id'=>seo_url('#organization')],'itemOffered'=>['@type'=>'Place','name'=>$display,'address'=>['@type'=>'PostalAddress','addressLocality'=>$project['location'],'addressRegion'=>'Punjab','addressCountry'=>'PK']]]:[];
?><!DOCTYPE html><html lang="en-PK"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?=seo_meta_tags(['title'=>$title,'description'=>$description,'canonical'=>$canonical,'image'=>$cover,'robots'=>$project?null:'noindex,follow'])?><base href="<?=seo_h(seo_site_url().'/')?>"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="project.css?v=20260907-6"><link rel="stylesheet" href="seo.css"><link rel="stylesheet" href="chatbot.css"><link rel="stylesheet" href="liquid-glass.css"><link rel="stylesheet" href="navigation-fixes.css"><link rel="stylesheet" href="footer-compact.css"><?=seo_json_ld(seo_breadcrumb_schema($crumbs))?><?=$project?seo_json_ld($schema):''?></head><body class="project-body">
<header class="site-header"><a class="brand" href="./"><span class="brand-logo"><img src="images/home-logo.jpg" alt="Heera Estate logo" width="56" height="56"></span><span>Heera Estate</span></a><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button><nav class="main-nav" aria-label="Main navigation"><a href="./">Home</a><a href="./?listing=sale#listings">Buy</a><a href="./?listing=rent#listings">Rent</a><a href="./?listing=installment#listings">Installments</a><a href="./#agents">Agents</a><div class="projects-nav"><button class="projects-toggle is-active" type="button" aria-expanded="false">Projects <span>⌄</span></button><div class="projects-menu" id="projectsMenu"></div></div><a href="plot-finder.html">PLOT FINDER</a><a href="./#contact">Contact</a>
      <a class="nav-add-property" href="add-property.html">Add Property</a><a class="login-button nav-login-item" href="./#admin-login">Login</a>
    </nav></header>
<?php if(!$project):?><main><section class="project-not-found section"><h1>Project not found</h1><p>This subproject is not public yet. In Admin, set both its parent project and the subproject to Published, then save again.</p><a class="button button-dark" href="./">Return home</a></section></main><?php else:?>
<nav class="seo-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="./">Home</a></li><li><a href="./#projects">Projects</a></li><li aria-current="page"><?=seo_h($display)?></li></ol></nav>
<main id="projectContent">
  <section class="project-hero" id="projectHero" style="background-image:linear-gradient(90deg,rgba(23,38,33,.72),rgba(23,38,33,.2)),url('<?=seo_h($cover)?>')"><div class="project-hero-inner"><p class="eyebrow light" id="projectCategory"><?=seo_h($subProjectName!==''?$project['title']:($project['plan_name']?'Plan: '.$project['plan_name']:$project['category']))?></p><h1 id="projectTitle"><?=seo_h($subProjectName?:$project['title'])?></h1><p class="project-location" id="projectLocation"><?=seo_h($project['location'])?></p></div></section>
  <section class="project-overview section"><div><p class="eyebrow" id="projectOverviewEyebrow"><?=seo_h($subProjectName!==''?'About the sub-project':'About the project')?></p><h2 id="projectHeadline"><?=seo_h($subProjectName?:($project['headline']?:$project['title']))?></h2></div><div class="project-copy"><p id="projectDescription"><?=seo_h(($selectedSubProject['description']??'')?:$project['description'])?></p><dl class="project-facts" id="projectFacts"></dl></div></section>
  <section class="project-subprojects section" id="subProjectsSection"<?=empty($project['sub_projects'])?' hidden':''?>><div class="section-heading"><div><p class="eyebrow">Project structure</p><h2>Sub-Projects &amp; Blocks</h2></div></div><div class="sub-project-public-grid" id="projectSubProjects"><?php foreach($project['sub_projects'] as $sub):$subSlug=trim((string)($sub['slug']??''));$subHref=$subSlug!==''?'sub-project/'.$subSlug:'project.php?sub_project_id='.(int)$sub['sub_project_id'];?><a class="sub-project-public-card<?=((int)$sub['sub_project_id']===(int)($selectedSubProject['sub_project_id']??0))?' is-active':''?>" href="<?=seo_h($subHref)?>"<?=((int)$sub['sub_project_id']===(int)($selectedSubProject['sub_project_id']??0))?' aria-current="page"':''?>><p class="eyebrow">Published</p><h3><?=seo_h($sub['name'])?></h3><?php if(!empty($sub['description'])):?><p><?=seo_h(seo_description($sub['description'],130))?></p><?php endif;?></a><?php endforeach;?></div></section>
  <section class="project-plans section" id="plansSection"<?=empty($project['payment_plans'])?' hidden':''?>><div class="section-heading"><div><p class="eyebrow">Plans</p><h2>Explore the layouts</h2></div></div><div class="plans-grid" id="projectPlans"><?php foreach($project['payment_plans'] as $plan):?><article class="plan-card"><p class="eyebrow"><?=seo_h($plan['sub_project_name']??'Payment plan')?></p><h3><?=seo_h($plan['plan_name']??($plan['size_label']??'Property plan'))?></h3><?php if(!empty($plan['size_label'])):?><p><?=seo_h($plan['size_label'])?></p><?php endif;?><?php if((float)($plan['total_price']??0)>0):?><strong>PKR <?=number_format((float)$plan['total_price'],0)?></strong><?php endif;?></article><?php endforeach;?></div></section>
  <section class="project-properties section" id="propertiesSection"<?=empty($project['properties'])?' hidden':''?>><div class="section-heading"><div><p class="eyebrow">Available listings</p><h2><?=seo_h($subProjectName!==''?'Properties in '.$subProjectName:'Properties in this project')?></h2></div></div><div class="project-properties-grid" id="projectProperties"><?php foreach(($project['properties']??[]) as $property):$propertyHref=!empty($property['slug'])?'property/'.$property['slug']:'property.php?id='.(int)$property['property_id'];?><article class="project-property-card"><a class="project-property-image" href="<?=seo_h($propertyHref)?>"><?php if(!empty($property['image_url'])):?><img src="<?=seo_h($property['image_url'])?>" alt="<?=seo_h($property['title'])?>" loading="lazy" decoding="async"><?php else:?><span>No image uploaded</span><?php endif;?></a><div><p class="eyebrow"><?=seo_h(seo_listing_label($property['listing_type']??''))?></p><h3><a href="<?=seo_h($propertyHref)?>"><?=seo_h($property['title'])?></a></h3><p><?=seo_h(implode(' · ',array_filter([$property['block_name']??'', $property['size_label']??'', $property['city']??''])))?></p><strong><?=seo_h(seo_property_price($property))?></strong></div></article><?php endforeach;?></div></section>
  <section class="project-gallery section"><div class="section-heading"><div><p class="eyebrow">Gallery</p><h2>Inside the project</h2></div></div><div class="project-gallery-grid" id="projectGallery"><?php foreach($project['media'] as $m)if($m['media_type']==='gallery'):?><figure><a href="<?=seo_h($m['file_path'])?>" target="_blank" rel="noopener" aria-label="Open full-size project image"><img src="<?=seo_h($m['file_path'])?>" alt="<?=seo_h($m['caption']?:$display)?>" loading="lazy" decoding="async" width="1000" height="750"></a></figure><?php endif;?></div></section>
  <section class="project-map-cta section"><div><p class="eyebrow">Digital location map</p><h2>Find a plot on the master plan</h2></div><a class="button button-primary" href="plot-finder.html">Open Plot Finder →</a></section>
  <section class="seo-related"><h2>Explore <?=seo_h($project['location'])?></h2><a href="location/<?=seo_h(seo_slugify($project['location']))?>">See more properties and projects in this location →</a></section>
</main><?php endif;?>
<section id="projectNotFound" hidden></section><footer class="site-footer"><a class="brand footer-brand" href="./"><span>Heera Estate</span></a><p>Homes that feel like home.</p><span>© <span id="year"><?=date('Y')?></span> Heera Real Estate</span></footer><?php if($project):?><script>window.__PROJECT_DATA__=<?=json_encode($project,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_HEX_TAG)?>;</script><?php endif;?><script src="site-nav.js?v=20260908-1"></script><script src="project.js?v=20260908-1"></script><script src="chatbot.js" defer></script><script src="theme.js" defer></script><?=seo_analytics()?></body></html>
