<?php
declare(strict_types=1); require_once __DIR__.'/seo.php';
$slug=trim((string)($_GET['slug']??''));$id=(int)($_GET['id']??0);
try{$project=seo_fetch_project(seo_db(),$slug?:null,$id);}catch(Throwable $e){$project=null;}
if(!$project)http_response_code(404);if($project&&$slug===''&&$id>0){header('Location: '.seo_url('project/'.$project['slug']),true,301);exit;}
$display=$project?trim($project['title'].' '.($project['plan_name']??'')):'';$title=$project?$display.' | '.seo_site_name():'Project not found | '.seo_site_name();$description=$project?seo_description($project['description']?:($project['category'].' project in '.$project['location'])):'The requested project is unavailable.';$canonical=$project?seo_url('project/'.$project['slug']):seo_url('project');$cover=$project?($project['hero_image_url']?:($project['media'][0]['file_path']??'')):'';
$crumbs=[['name'=>'Home','url'=>seo_url()],['name'=>'Projects','url'=>seo_url('#projects')]];if($project)$crumbs[]=['name'=>$display,'url'=>$canonical];
$schema=$project?['@context'=>'https://schema.org','@type'=>'RealEstateListing','name'=>$display,'description'=>$description,'url'=>$canonical,'image'=>seo_asset_url($cover),'dateModified'=>$project['updated_at'],'itemOffered'=>['@type'=>'Residence','name'=>$display,'address'=>['@type'=>'PostalAddress','addressLocality'=>$project['location'],'addressCountry'=>'PK']]]:[];
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?=seo_meta_tags(['title'=>$title,'description'=>$description,'canonical'=>$canonical,'image'=>$cover,'robots'=>$project?null:'noindex,follow'])?><base href="<?=seo_h(seo_site_url().'/')?>"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="project.css"><link rel="stylesheet" href="seo.css"><link rel="stylesheet" href="chatbot.css"><link rel="stylesheet" href="client-button.css"><link rel="stylesheet" href="liquid-glass.css"><link rel="stylesheet" href="navigation-fixes.css"><link rel="stylesheet" href="footer-compact.css"><?=seo_json_ld(seo_breadcrumb_schema($crumbs))?><?=$project?seo_json_ld($schema):''?></head><body class="project-body">
<header class="site-header"><a class="brand" href="./"><span class="brand-logo"><img src="images/home-logo.jpg" alt="Heera Estate logo" width="56" height="56"></span><span>Heera Estate</span></a><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button><nav class="main-nav" aria-label="Main navigation"><a href="./">Home</a><a href="./?listing=sale#listings">Buy</a><a href="./?listing=rent#listings">Rent</a><a href="./#agents">Agents</a><div class="projects-nav"><button class="projects-toggle is-active" type="button" aria-expanded="false">Projects <span>⌄</span></button><div class="projects-menu" id="projectsMenu"></div></div><a href="plot-finder.html">PLOT FINDER</a><a href="./#contact">Contact</a></nav><div class="header-actions"><a class="client-form-button" href="client-form.html">Client Form <span>＋</span></a><a class="admin-login-icon login-button" href="./#admin-login">Login</a></div></header>
<?php if(!$project):?><main><section class="project-not-found section"><h1>Project not found</h1><p>This project is not published or no longer exists.</p><a class="button button-dark" href="./">Return home</a></section></main><?php else:?>
<nav class="seo-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="./">Home</a></li><li><a href="./#projects">Projects</a></li><li aria-current="page"><?=seo_h($display)?></li></ol></nav><main id="projectContent"><section class="project-hero" id="projectHero" style="background-image:linear-gradient(90deg,rgba(23,38,33,.72),rgba(23,38,33,.2)),url('<?=seo_h($cover)?>')"><div class="project-hero-inner"><p class="eyebrow light" id="projectCategory"><?=seo_h($project['plan_name']?'Plan: '.$project['plan_name']:$project['category'])?></p><h1 id="projectTitle"><?=seo_h($project['title'])?></h1><p class="project-location" id="projectLocation"><?=seo_h($project['location'])?></p></div></section><section class="project-overview section"><div><p class="eyebrow">About the project</p><h2 id="projectHeadline"><?=seo_h($project['headline']?:$project['title'])?></h2></div><div class="project-copy"><p id="projectDescription"><?=seo_h($project['description'])?></p><dl class="project-facts" id="projectFacts"></dl></div></section><section class="project-plans section" id="plansSection"><div class="section-heading"><div><p class="eyebrow">Plans</p><h2>Explore the layouts</h2></div></div><div class="plans-grid" id="projectPlans"></div></section><section class="project-gallery section"><div class="section-heading"><div><p class="eyebrow">Gallery</p><h2>Inside the project</h2></div></div><div class="project-gallery-grid" id="projectGallery"><?php foreach($project['media'] as $m)if($m['media_type']==='gallery'):?><figure><img src="<?=seo_h($m['file_path'])?>" alt="<?=seo_h($m['caption']?:$display)?>" loading="lazy" decoding="async" width="1000" height="750"></figure><?php endif;?></div></section><section class="project-map-cta section"><div><p class="eyebrow">Digital location map</p><h2>Find a plot on the master plan</h2></div><a class="button button-primary" href="plot-finder.html">Open Plot Finder →</a></section><section class="seo-related"><h2>Explore <?=seo_h($project['location'])?></h2><a href="location/<?=seo_h(seo_slugify($project['location']))?>">See more properties and projects in this location →</a></section></main><?php endif;?>
<section id="projectNotFound" hidden></section><footer class="site-footer"><a class="brand footer-brand" href="./"><span>Heera Estate</span></a><p>Homes that feel like home.</p><span>© <span id="year"><?=date('Y')?></span> Heera Real Estate</span></footer><?php if($project):?><script>window.__PROJECT_DATA__=<?=json_encode($project,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_HEX_TAG)?>;</script><?php endif;?><script src="site-nav.js"></script><script src="project.js"></script><script src="chatbot.js" defer></script><script src="theme.js" defer></script><?=seo_analytics()?></body></html>
