<?php
declare(strict_types=1);
require_once __DIR__ . '/seo.php';
$slug = trim((string)($_GET['slug'] ?? ''));
$id = (int)($_GET['id'] ?? $_GET['property_id'] ?? 0);
try { $property = seo_fetch_property(seo_db(), $slug ?: null, $id); } catch (Throwable $e) { $property = null; }
if (!$property) http_response_code(404);
if ($property && $slug === '' && $id > 0) { header('Location: ' . seo_url('property/' . $property['slug']), true, 301); exit; }
$title = $property ? $property['title'] . ' in ' . $property['city'] . ' | ' . seo_site_name() : 'Property not found | ' . seo_site_name();
$description = $property ? seo_description($property['description'] ?: ($property['property_type'] . ' for ' . $property['listing_type'] . ' in ' . $property['city'] . '. ' . seo_property_price($property) . '.')) : 'The requested property is not currently available.';
$images = $property ? array_values(array_filter($property['media'], fn($m) => $m['media_type'] === 'image')) : [];
$cover = $images[0]['file_path'] ?? 'images/al-rehman-garden-hero.png';
$canonical = $property ? seo_url('property/' . $property['slug']) : seo_url('property');
$address = $property ? implode(', ', array_filter([$property['address_line1'], $property['city'], $property['state_region'], $property['postal_code']])) : '';
$breadcrumbs = [['name'=>'Home','url'=>seo_url()],['name'=>'Properties','url'=>seo_url('#listings')]];
if ($property) $breadcrumbs[] = ['name'=>$property['title'],'url'=>$canonical];
$schema = $property ? [
  '@context'=>'https://schema.org','@type'=>'RealEstateListing','name'=>$property['title'],'description'=>$description,'url'=>$canonical,
  'image'=>array_map(fn($m)=>seo_asset_url($m['file_path']), $images),'datePosted'=>$property['created_at'],'dateModified'=>$property['updated_at'],
  'offers'=>['@type'=>'Offer','price'=>(float)($property['price_pkr'] ?: $property['price'] ?: 0),'priceCurrency'=>$property['price_pkr'] ? 'PKR' : 'USD','availability'=>'https://schema.org/InStock','url'=>$canonical],
  'itemOffered'=>['@type'=>'Accommodation','name'=>$property['title'],'numberOfBedrooms'=>$property['bedrooms'] ?: null,'numberOfBathroomsTotal'=>$property['bathrooms'] ?: null,'floorSize'=>$property['area_sqft'] ? ['@type'=>'QuantitativeValue','value'=>(float)$property['area_sqft'],'unitCode'=>'FTK'] : null,'address'=>['@type'=>'PostalAddress','streetAddress'=>$property['address_line1'],'addressLocality'=>$property['city'],'addressRegion'=>$property['state_region'],'postalCode'=>$property['postal_code'],'addressCountry'=>'PK']]
] : [];
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <?= seo_meta_tags(['title'=>$title,'description'=>$description,'canonical'=>$canonical,'image'=>$cover,'type'=>'product','robots'=>$property ? null : 'noindex,follow']) ?>
  <base href="<?= seo_h(seo_site_url() . '/') ?>"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="property.css"><link rel="stylesheet" href="seo.css"><link rel="stylesheet" href="chatbot.css"><link rel="stylesheet" href="client-button.css"><link rel="stylesheet" href="liquid-glass.css"><link rel="stylesheet" href="navigation-fixes.css"><link rel="stylesheet" href="footer-compact.css">
  <?= seo_json_ld(seo_breadcrumb_schema($breadcrumbs)) ?><?= $property ? seo_json_ld($schema) : '' ?>
</head><body class="property-detail-page">
<header class="site-header property-header"><a class="brand" href="./" aria-label="Heera Estate home"><span class="brand-logo"><img src="images/home-logo.jpg" alt="Heera Estate logo" width="56" height="56"></span><span>Heera Estate</span></a><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button><nav class="main-nav" aria-label="Main navigation"><a href="./">Home</a><a href="./?listing=sale#listings">Buy</a><a href="./?listing=rent#listings">Rent</a><a href="./#agents">Agents</a><div class="projects-nav"><button class="projects-toggle" type="button" aria-expanded="false">Projects <span>⌄</span></button><div class="projects-menu" id="projectsMenu"><span class="projects-loading">Loading projects…</span></div></div><a href="plot-finder.html">PLOT FINDER</a><a href="./#contact">Contact</a></nav><div class="header-actions"><a class="client-form-button" href="client-form.html">Client Form <span>＋</span></a><a class="admin-login-icon login-button" href="./#admin-login">Login</a></div></header>
<main>
<?php if (!$property): ?><section class="property-state property-error"><p class="eyebrow">Property unavailable</p><h1>We couldn’t find this property.</h1><p>It may have expired, sold, or been removed.</p><a class="button button-primary" href="./#listings">View available properties <span>→</span></a></section>
<?php else: ?>
<nav class="seo-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="./">Home</a></li><li><a href="./#listings">Properties</a></li><li aria-current="page"><?= seo_h($property['title']) ?></li></ol></nav>
<section class="property-state" id="propertyLoading" hidden></section><section class="property-state property-error" id="propertyError" hidden><h1 id="propertyErrorTitle"></h1><p id="propertyErrorMessage"></p></section>
<article id="propertyContent"><section class="property-intro"><div class="property-intro-copy"><div class="property-badges"><span class="property-badge property-badge-primary" id="propertyListingType">For <?= seo_h($property['listing_type']) ?></span><span class="property-badge" id="propertyType"><?= seo_h($property['property_type']) ?></span><span class="property-badge" id="propertyStatus"><?= seo_h($property['status']) ?></span></div><h1 id="propertyTitle"><?= seo_h($property['title']) ?></h1><p class="property-location" id="propertyLocation"><?= seo_h($address) ?></p></div><div class="property-price-panel"><span>Property price</span><strong id="propertyPrice"><?= seo_h(seo_property_price($property)) ?></strong><small id="propertySecondaryPrice" hidden></small></div></section>
<section class="property-gallery-section" aria-label="Property media"><div class="property-main-media" id="propertyMainMedia"><?php if ($images): ?><img src="<?= seo_h($images[0]['file_path']) ?>" alt="<?= seo_h($property['title']) ?>" width="1200" height="800" fetchpriority="high" decoding="async"><?php endif; ?></div><button class="property-gallery-arrow property-gallery-previous" id="previousMedia" type="button" aria-label="Previous image" hidden>‹</button><button class="property-gallery-arrow property-gallery-next" id="nextMedia" type="button" aria-label="Next image" hidden>›</button><span class="property-gallery-count" id="mediaCount" hidden></span></section><div class="property-thumbnails" id="propertyThumbnails"></div>
<section class="property-information"><div class="property-main-column"><section class="property-block"><p class="eyebrow">Overview</p><h2>Property details</h2><div class="property-facts" id="propertyFacts"></div></section><section class="property-block" id="descriptionSection"><p class="eyebrow">About this property</p><h2>Description</h2><p class="property-description-text" id="propertyDescription"><?= seo_h($property['description']) ?></p></section><section class="property-block" id="videoSection" hidden><h2>Property videos</h2><div class="property-video-grid" id="propertyVideos"></div></section><section class="property-block" id="linksSection" hidden><h2>Property links</h2><div id="propertyLinks"></div></section></div><aside class="property-contact-card"><p class="eyebrow">Interested?</p><h2>Ask about this property</h2><p>Mention property <strong id="propertyReference">#<?= (int)$property['property_id'] ?></strong>.</p><a class="button button-primary property-contact-button" id="whatsAppEnquiry" href="https://wa.me/923000660446" target="_blank" rel="noopener">Enquire on WhatsApp <span>→</span></a><a class="property-contact-secondary" href="./#contact">Send an enquiry</a></aside></section></article>
<section class="seo-related"><h2>Explore more in <?= seo_h($property['city']) ?></h2><a href="location/<?= seo_h(seo_slugify($property['city'])) ?>">View properties and projects in <?= seo_h($property['city']) ?> →</a></section>
<?php endif; ?></main>
<footer class="site-footer"><a class="brand footer-brand" href="./"><span class="brand-logo"><img src="images/home-logo.jpg" alt="Heera Estate logo" width="56" height="56"></span><span>Heera Estate</span></a><p>Homes that feel like home.</p><span>© <span id="year"><?= date('Y') ?></span> Heera Estate</span></footer>
<?php if ($property): ?><script>window.__PROPERTY_DATA__=<?= json_encode($property, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_HEX_TAG) ?>;</script><?php endif; ?><script src="site-nav.js"></script><script src="property.js"></script><script src="chatbot.js" defer></script><script src="theme.js" defer></script><?= seo_analytics() ?></body></html>
